# Generated by Django 5.1 on 2024-10-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('n', models.IntegerField(auto_created=True, serialize=False)),
                ('numero_inscription', models.IntegerField()),
                ('matricule', models.IntegerField()),
                ('nom', models.CharField(max_length=500)),
                ('prenom', models.CharField(max_length=500)),
                ('section', models.IntegerField()),
                ('groupe', models.IntegerField()),
                ('bac_year', models.IntegerField()),
            ],
        ),
    ]
