# Generated by Django 5.1 on 2024-10-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bac_year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='groupe',
        ),
        migrations.AddField(
            model_name='student',
            name='annee_bac',
            field=models.CharField(default=2023, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='group_actual',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='matricule',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='n',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='numero_inscription',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='prenom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.CharField(max_length=100),
        ),
    ]
