# Generated by Django 5.1 on 2024-10-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_groups', '0002_remove_student_bac_year_remove_student_groupe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='annee_bac',
            new_name='bac_year',
        ),
    ]
